# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7881a852d485bbfe696bc117c5fc01aaaeafa74180ba410cf5177674eebaee9aa2a39d83ba520f3a089333c7d6bf21906a835b21b7c4ef3089d37f16ea0508d

test:
  secret_key_base: 76a0b78a1a0bd5f3858badf99f7bf9bf525e65a036fd2ee41f1fd9461fe94183966ad491b663b29d6a6f06ab29469069216379f7eb73a1f4ed5bb6b1691eb6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
